### ISSUE TITLE
你好，想问下现在会看机会吗，我这边是有今日头条的职位想和你介绍

### ISSUE THREAD

**Issue by dreamyboy** [tuxlinuxien/TwistedWebsocket#1]
服务端开发工程师
20k ~ 40k 北京 3-5年 社招 / 全职 1人
职位描述：
1、负责今日头条相关产品的后台业务研发；
2、负责在线大流量高并发系统设计；
3、主要实现语言为Python／Golang。
职位要求：
1、统招本科及以上学历，计算机、通信等相关专业者优先；
2、有扎实的编程能力，有优秀的设计和代码品味； 
3、深刻理解计算机原理，有良好的数据结构和算法基础； 
4、熟悉Mysql、Nosql、消息队列等常用WEB组件； 
5、有高并发服务设计和实现经验优先； 
6、有较好的产品意识优先； 
7、积极乐观，责任心强，工作认真细致，有良好的团队沟通和协作能力； 
8、热爱编程，有较强的学习能力，有强烈的求知欲、好奇心和进取心，能及时关注和学习业界最新技术。

如果有兴趣可以和我联系~

**Comment by tuxlinuxien** [comment]
I don't think it's the right place for this kind of messages. Enjoy your ban.
